import type { Award } from "../types";

export const awards: Award[] = [
  {
    id: "awd_outstanding_contribution",
    slug: "outstanding-contribution-award",
    title: "Outstanding Contribution Award",
    issuer: "UBS",
    date: { year: 2022, month: 4 },
    summary: "For resolving a major production outage in record time.",
    body: `Awarded for resolving a Sev-1 production outage that had blocked customer access. The resolution also retired a legacy tech debt so the same failure can never happen again.`,
    sourceExperienceId: "exp_ubs_swe",
    storyId: "story_cipher_suite",
    skillIds: [
      "skl_ssl_tls",
      "skl_incident_response",
      "skl_microservices",
      "skl_rest_soap",
      "skl_java",
      "skl_spring_boot",
    ],
    iconName: "trophy",
    featured: true,
    order: 1,
    visibility: "public",
  },
  {
    id: "awd_engineering_excellence",
    slug: "engineering-excellence-award",
    title: "Engineering Excellence Award",
    issuer: "UBS",
    date: { year: 2022, month: 8 },
    summary:
      "Awarded for becoming a core part of the team within my first year, building financial applications, resolving production incidents, and engineering inventive solutions to complex problems.",
    body: `Awarded for becoming a core part of the team within my first year at UBS, straight out of university, building and maintaining financial applications, resolving production incidents, and engineering inventive solutions to complex problems.`,
    sourceExperienceId: "exp_ubs_swe",
    storyId: "story_reverse_routing",
    skillIds: [
      "skl_spring_boot",
      "skl_react",
      "skl_java",
      "skl_jsp",
      "skl_microservices",
      "skl_perf_optimization",
      "skl_system_design",
      "skl_ssl_tls",
    ],
    iconName: "award",
    featured: true,
    order: 2,
    visibility: "public",
  },
  {
    id: "awd_cdio_champion",
    slug: "cdio-champion-award",
    title: "CDIO Champion Award",
    issuer: "UBS",
    date: { year: 2022, month: 12 },
    summary:
      "For leadership and coordination across cultural activities, celebrations and sports tournaments.",
    body: `Awarded for leadership across the departmental cultural committees: budget management, logistics, and running events from planning through execution. It built genuine strong relationships across the workplace, and made the office more fun to work at.`,
    sourceExperienceId: "exp_ubs_swe",
    skillIds: ["skl_mentorship"],
    iconName: "handshake",
    featured: true,
    order: 3,
    visibility: "public",
  },
  {
    id: "awd_above_beyond",
    slug: "going-above-and-beyond-award",
    title: "Going Above and Beyond Award",
    issuer: "UBS",
    date: { year: 2024, month: 4 },
    summary:
      "For closing critical compliance gaps, migrating batch applications to the cloud, and rebuilding file-transfer infrastructure.",
    body: `Awarded for closing critical compliance gaps across financial applications, migrating batch jobs to the cloud, upgrading file-transfer infrastructure, and refactoring applications for a 40% performance gain in production.`,
    sourceExperienceId: "exp_ubs_swe",
    storyId: "story_halted_the_vendor",
    skillIds: [
      "skl_cloud_migration",
      "skl_azure",
      "skl_linux",
      "skl_perf_optimization",
      "skl_cicd",
      "skl_autosys",
      "skl_java",
      "skl_spring_boot",
      "skl_microservices",
      "skl_agile",
    ],
    iconName: "zap",
    featured: true,
    order: 4,
    visibility: "public",
  },
  {
    id: "awd_promotion_ao",
    slug: "authorized-officer-promotion",
    title: "Promotion to Authorized Officer",
    issuer: "UBS",
    date: { year: 2024, month: 2 },
    summary:
      "Corporate title promotion following two years of delivery and informal recognition as an SSL/TLS specialist and Subject Matter Expert for the application.",
    body: `Promoted to Authorized Officer after two years of delivery: resolving production incidents, building out application infrastructure, optimizing performance, shrinking server footprint, and leading cloud migration. Along the way, the team came to know me informally as its SSL/TLS specialist and, as a subject matter expert on the application.`,
    sourceExperienceId: "exp_ubs_swe",
    storyId: "story_one_week_became_four",
    skillIds: [
      "skl_java",
      "skl_spring_boot",
      "skl_linux",
      "skl_cloud_migration",
      "skl_azure",
      "skl_incident_response",
      "skl_microservices",
      "skl_ssl_tls",
      "skl_system_design",
    ],
    iconName: "star",
    featured: false,
    order: 5,
    visibility: "public",
  },
  {
    id: "awd_iot_finalist",
    slug: "iot-challenge-finalist",
    title: "IoT Challenge Finalist",
    issuer: "i3indya Technologies",
    date: { year: 2019, month: 9 },
    rank: "Finalist",
    summary:
      "Selected as a finalist to present the Smart Society project at IoT Challenge 2020, IIT Bombay.",
    body: `Selected as a finalist to present the Smart Society project, an automated disaster-detection system that cut emergency response delays by 47%, at i3indya's IoT Challenge 2020, hosted at IIT Bombay. The final round never happened; the event was cancelled by the pandemic but it was a valuable experience.`,
    sourceProjectIds: ["prj_smart_society"],
    skillIds: [
      "skl_atmega",
      "skl_java",
      "skl_react",
      "skl_firebase",
      "skl_system_design",
      "skl_c_cpp",
    ],
    iconName: "flag",
    featured: false,
    order: 6,
    visibility: "public",
  },
];
