import type { Experience } from "../types";

/**
 * `highlights` carries the resume-register XYZ bullets: impact first, numbers
 * where they exist, written so they can be lifted straight onto a résumé.
 * Same split as Project. Narrative belongs in the stories.
 *
 * `body` is optional prose above the bullets and is unused today — no role
 * has needed a paragraph of context yet.
 * `achievements` is retained for a distinct UI treatment.
 */
export const experiences: Experience[] = [
  // ── PHASE: POST-MASTER'S ─────────────────────────────────────────
  {
    id: "exp_llm_re_research",
    slug: "decompiler-evaluation-for-llm-vulnerability-discovery",
    role: "Volunteer Research Assistant — Decompiler Evaluation for LLM Vulnerability Discovery",
    org: "Noelo Lab, University of Georgia",
    orgUrl: "https://noelo.org",
    type: "research",
    mode: "remote",
    location: "Remote",
    date: { start: { year: 2026, month: 6 }, end: null },
    summary:
      "Testing whether decompiler choice changes an LLM agent's ability to find real vulnerabilities.",
    highlights: [
      "Designed and ran controlled experiments measuring whether decompiler choice affects an MCP-connected LLM agent's ability to independently discover vulnerabilities in binaries.",
      "Achieved 100% ground-truth consistency across decompilers by designing an address-anchored system to normalize output with incompatible naming conventions.",
      "Reduced experimental data processing time by 89% through an automated Python pipeline to parse 100,000+ session log lines and compute discovery-efficiency metrics, context efficiency ratio, tool-call efficiency, and address recall, across dozens of experimental runs.",
      "Resolved inconsistent vulnerability classifications across identical runs by designing a three-axis grading rubric separating localization, classification, and exploitation.",
      "Established baseline LLM performance metrics through a 5-run pilot study, demonstrating agent localization accuracy consistently outperforms classification accuracy.",
    ],
    achievements: [],
    skillIds: [
      "skl_reverse_engineering",
      "skl_vuln_research",
      "skl_ml_security",
      "skl_ghidra_ida",
      "skl_python",
      "skl_c_cpp",
      "skl_binary_exploitation",
      "skl_threat_modeling",
    ],
    links: [],
    phaseId: "phase_post_masters",
    featured: true,
    order: 1,
    visibility: "public",
  },
  {
    id: "exp_barnum",
    slug: "performance-ai-observability-dashboard",
    role: "Volunteer Engineer — Performance AI",
    org: "ASU CIPS-AI Lab",
    type: "volunteer",
    mode: "onsite",
    location: "Tempe, AZ",
    date: { start: { year: 2026, month: 7 }, end: { year: 2026, month: 8 } },
    summary: "Built an observability dashboard for a multi-agent AI system",
    highlights: [
      "Built a comprehensive observability UI for a multi-service AI system (FastAPI, LangGraph, OpenTelemetry), integrating React/TypeScript front-end panels with backend services to render 20 live metric tiles tracking drift-detection and model quality.",
      "Resolved critical infrastructure pipeline failures by debugging Helm configurations and tracing a cluster-wide Docker/cri-dockerd symlink resolution gap in DaemonSet volume mounts via direct Kubernetes node log inspection.",
      "Restored end-to-end telemetry data flow by rectifying Collector processing rules and fixing a backend SQL data-normalization defect, recovering 40% of drift-detection metrics.",
    ],
    achievements: [],
    skillIds: [
      "skl_react",
      "skl_typescript",
      "skl_kubernetes",
      "skl_docker",
      "skl_python",
      "skl_sql",
      "skl_linux",
      "skl_system_design",
      "skl_cloud",
      "skl_ml_security",
    ],
    links: [],
    phaseId: "phase_post_masters",
    featured: false,
    order: 2,
    visibility: "public",
  },

  // ── PHASE: MASTER'S ──────────────────────────────────────────────
  {
    id: "exp_asu_ta",
    slug: "graduate-teaching-assistant-software-security",
    role: "Teaching Assistant — Software Security",
    org: "Arizona State University",
    orgUrl: "https://scai.engineering.asu.edu/",
    type: "academic",
    mode: "onsite",
    location: "Tempe, AZ",
    date: { start: { year: 2025, month: 8 }, end: { year: 2026, month: 5 } },
    summary:
      "Mentored graduate students in systems security and reverse engineering, and built the isolated CTF architecture their exams ran on.",
    highlights: [
      "Mentored over 150 students in memory corruption and reverse engineering by developing hands-on CTF challenges in C, Python, and Bash, incorporating threat modeling to simulate real-life attack vectors on the pwn.college platform.",
      "Maintained 100% exam security by engineering isolated CTF architectures in Docker, configuring Nginx reverse proxy, Python Flask authentication, and Landrun sandboxing to restrict IDE and terminal access, preventing unauthorized collaboration.",
      "Enhanced student proficiency in Return Oriented Programming, secure coding practices, and web and system security through 7+ hours of weekly guidance, scripting with pwntools, GNU Debugger, IDA, Wireshark, and Burp Suite for dynamic and static analysis.",
      "Lifted the class average from below 60% to approximately 80% by restructuring monolithic exploitation labs into progressive micro-challenges that isolated each concept before requiring composition.",
    ],
    achievements: [],
    skillIds: [
      "skl_binary_exploitation",
      "skl_reverse_engineering",
      "skl_c_cpp",
      "skl_python",
      "skl_bash",
      "skl_docker",
      "skl_landrun",
      "skl_linux",
      "skl_gdb",
      "skl_ghidra_ida",
      "skl_wireshark",
      "skl_threat_modeling",
      "skl_kernel_security",
      "skl_mentorship",
      "skl_secure_coding",
      "skl_flask",
    ],
    links: [
      {
        kind: "external",
        url: "https://pwn.college/cse545-fc25~dc4e237e/",
        label: "Course modules — Fall 2025",
      },
      {
        kind: "external",
        url: "https://pwn.college/cse545-sc26~7ec2f341/",
        label: "Course modules — Spring 2026",
      },
    ],
    phaseId: "phase_masters",
    featured: true,
    order: 3,
    visibility: "public",
  },

  // ── PHASE: UBS ───────────────────────────────────────────────────
  {
    id: "exp_ubs_swe",
    slug: "software-engineer-ubs",
    role: "Software Engineer",
    org: "UBS",
    orgUrl: "https://www.ubs.com",
    type: "full-time",
    mode: "onsite",
    location: "Pune, India",
    date: { start: { year: 2021, month: 7 }, end: { year: 2024, month: 6 } },
    summary:
      "Modernizing and defending financial applications, building backend architecture, migrating to cloud migration, and hardening application security.",
    highlights: [
      "Modernized Java application architecture and minimized operational errors by 99% through Drools workflow refactoring and decoupling Spring Web MVC monoliths into distributed React and Spring Boot microservices.",
      "Led infrastructure migrations to Azure and ensured business continuity, maintaining 99.9% availability through rapid incident response for critical production outages, Unix server management, and GitLab pipeline engineering.",
      "Boosted service performance by 53% and accelerated data processing by consolidating REST API requests and optimizing SQL queries for MySQL and Postgres databases.",
      "Hardened system security by enforcing SSL/TLS encryption across API endpoints and implementing a least-privilege access model by migrating hardcoded credentials to an EVA Vault using RBAC profiles.",
      "Improved batch application performance by 40% through targeted code refactoring, and migrated enterprise file transfer infrastructure from Tumbleweed to Axway.",
    ],
    achievements: [
      "Outstanding Contribution Award",
      "Engineering Excellence Award",
      "CDIO Champion Award",
      "Going Above and Beyond Award",
      "Promotion to Authorized Officer/SDE II",
    ],
    skillIds: [
      "skl_java",
      "skl_spring_boot",
      "skl_jsp",
      "skl_react",
      "skl_drools",
      "skl_sql",
      "skl_postgres",
      "skl_azure",
      "skl_cicd",
      "skl_linux",
      "skl_bash",
      "skl_git",
      "skl_autosys",
      "skl_vault",
      "skl_ssl_tls",
      "skl_rest_soap",
      "skl_microservices",
      "skl_incident_response",
      "skl_perf_optimization",
      "skl_cloud_migration",
      "skl_secure_coding",
      "skl_system_design",
      "skl_technical_writing",
      "skl_agile",
    ],
    links: [],
    phaseId: "phase_ubs",
    featured: true,
    order: 4,
    visibility: "public",
  },
  {
    id: "exp_ubs_intern",
    slug: "software-engineering-intern-ubs",
    role: "Software Engineering Intern",
    org: "UBS",
    orgUrl: "https://www.ubs.com",
    type: "internship",
    mode: "onsite",
    location: "Pune, India",
    date: { start: { year: 2020, month: 6 }, end: { year: 2021, month: 1 } },
    summary:
      "Built samrt business forms and live web applications integrating SOAP and REST services, the internship that became a full-time role.",
    highlights: [
      "Designed and managed smart business forms using AEM Forms Designer, improving user experience and reducing document processing time by 25%.",
      "Engineered live web applications with Java and React, integrating with SOAP and REST APIs, resulting in a 20% increase in performance.",
    ],
    achievements: [],
    skillIds: [
      "skl_java",
      "skl_react",
      "skl_javascript",
      "skl_rest_soap",
      "skl_microservices",
    ],
    links: [],
    phaseId: "phase_ubs",
    featured: false,
    order: 5,
    visibility: "public",
  },

  // ── PHASE: UNDERGRAD ─────────────────────────────────────────────
  {
    id: "exp_cisco_academy",
    slug: "student-office-assistant-cisco-networking-academy",
    role: "Student Office Assistant & Division Head",
    org: "Cisco Networking Academy",
    type: "volunteer",
    mode: "onsite",
    location: "Pune, India",
    date: { start: { year: 2019, month: 7 }, end: { year: 2020, month: 5 } },
    summary:
      "Grew the campus networking cell as Division Head, recruiting and onboarding over 150 students through intra-division networking campaigns.",
    highlights: [
      "Grew the campus networking cell as Division Head, recruiting and onboarding over 150 students through intra-division networking campaigns.",
      "Mentored club members through the CCNA certification track, troubleshooting hands-on networking challenges and guiding them to course completion.",
      "Recognized by department faculty for driving technical domain awareness and advancing the club's core growth objectives across the 2019–2020 academic year.",
    ],
    achievements: [],
    skillIds: ["skl_network_security", "skl_mentorship"],
    links: [],
    phaseId: "phase_undergrad",
    featured: false,
    order: 6,
    visibility: "public",
  },
  {
    id: "exp_robotics_lab",
    slug: "student-lab-aide-advanced-robotics-lab",
    role: "Student Lab Aide",
    org: "Advanced Robotics Lab",
    type: "academic",
    mode: "onsite",
    location: "Pune, India",
    date: { start: { year: 2017, month: 7 }, end: { year: 2018, month: 5 } },
    summary: "Built robots on Arduino for Robocon and Mindspark competitions.",
    highlights: [
      "Developed robotics projects on Arduino microcontrollers for competitions including Robocon and Mindspark.",
      "Designed and programmed a four-legged robotic horse driven by servo motors on an Arduino microcontroller.",
      "Built a line-following robot using a Cytron 7-bit IR sensor and Arduino Nano.",
      "Contributed to development of a custom optical encoder for real-time bot speed detection.",
      "Collaborated with a team to design, test, and optimize robotic systems, ensuring high performance and reliability in competitive environments.",
    ],
    achievements: [],
    skillIds: ["skl_atmega", "skl_c_cpp"],
    links: [
      {
        kind: "github",
        url: "https://github.com/DhavalDDT/auto-bot2K19",
        label: "auto-bot2K19",
      },
      {
        kind: "github",
        url: "https://github.com/DhavalDDT/MR1-Traversal",
        label: "MR1-Traversal",
      },
      {
        kind: "github",
        url: "https://github.com/DhavalDDT/botwot",
        label: "botwot",
      },
    ],
    phaseId: "phase_undergrad",
    featured: false,
    order: 7,
    visibility: "public",
  },
  {
    id: "exp_instructional_assistant",
    slug: "instructional-assistant",
    role: "Instructional Assistant",
    org: "Private Coaching Centre",
    type: "part-time",
    mode: "onsite",
    location: "Pune, India",
    date: { start: { year: 2019, month: 8 }, end: { year: 2020, month: 12 } },
    summary:
      "Taught object-oriented programming in C++ and 8085 microcontroller assembly to senior high school students.",
    highlights: [
      "Tutored a cohort of 10–15 senior high school students in C++ and object-oriented programming over 17 months.",
      "Taught computer architecture and assembly-level programming on 8085 microprocessor, building students' foundation in low-level systems programming.",
      "Authored and graded examinations across the C++ and assembly curricula to assess student performance.",
    ],
    achievements: [],
    skillIds: ["skl_c_cpp", "skl_mentorship", "skl_x86_asm"],
    links: [],
    phaseId: "phase_undergrad",
    featured: false,
    order: 8,
    visibility: "public",
  },
  {
    id: "exp_nanostuffs",
    slug: "intern-nanostuffs",
    role: "Intern",
    org: "Nanostuffs Technologies Pvt. Ltd.",
    type: "internship",
    mode: "onsite",
    location: "Pune, India",
    date: { start: { year: 2019, month: 6 }, end: { year: 2019, month: 7 } },
    summary:
      "Designed system administration solutions for customer relationship management on the Salesforce platform.",
    highlights: [
      "Designed Salesforce workflow automations to manage lead follow-up, replacing manual tracking with system-triggered task assignments.",
      "Configured automated email sequences within Salesforce to maintain consistent follow-up communication, over a one-month internship.",
    ],
    achievements: [],
    skillIds: ["skl_system_design"],
    links: [],
    phaseId: "phase_undergrad",
    featured: false,
    order: 9,
    visibility: "public",
  },
];
